<?php

use Illuminate\Database\Seeder;

class RecipeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('recipes')->insert([
            array(
                'user_id' => '1',
                'video_id' => '1',
                'category_id' => '1',
                'featured' => 'features/video_1.mp4',
                'title' => 'Aloha Carrot Cake',
                'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Banana Cake',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Brownies',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Burger Buns',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Butterscotch',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Cheese Roll',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Choco Marble Cake',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Cinnamon Roll',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Crinkles',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Croissant',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Doughnut',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Eggless Butter Cookies',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Ensaymada',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Fresh Bread',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Loaf Bread',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Pandesal',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Peanut Butter Cookies',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Red Velvet Cupcake',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Siopao',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Sugar Cookies',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),
            array(
                'user_id' => '1',
                'video_id' => '2',
                'category_id' => '2',
                'featured' => 'features/video_2.mp4',
                'title' => 'Whole Wheat Bread',
                  'ingredients' => json_encode([
                    'ingredient 1',
                    'ingredient 2',
                    'ingredient 3',
                    'ingredient 4',
                    'ingredient 5'
                ]),
                'procedure' => json_encode([
                    'procedure 1',
                    'procedure 2',
                    'procedure 3',
                    'procedure 4',
                    'procedure 5',
                    'procedure 6',
                ]),
                'created_at' => Carbon\Carbon::now(),
                'updated_at' => Carbon\Carbon::now(),
            ),

        ]);
    }
}
